- hosts: all
  tasks:
          - name: Copying the Packages 
            copy:
                    src: /root/Hadoop_rpm/
                    dest: /root/
          
          - name: Installing the packages
            command: rpm -ivh jdk-8u171-linux-x64.rpm
            command: rpm -ivh hadoop-1.2.1-1.x86_64.rpm --force
          
- hosts: Namenode
  vars: 
        - name_dir: name_dir
  tasks:
          - name: Creating Namenode Directory
            file:
                    path: /"{{dir}}"
                    state: directory 
          - name: Updating the config files of Namenode
            template: 
                    src: hdfs-site-name.xml.j2
                    dest: /etc/hadoop/hdfs-site.xml
          - template:    
                    src: core-site-name.xml.j2
                    dest: /etc/hadoop/core-site.xml


          - name: Formatting & Starting Namenode
            command: hadoop namenode -format   -Y   
            command: hadoop-daemon.sh start namenode
- hosts: Datanodes
  vars:
          - data_dir: data_dir
  tasks:
          - name: Updating Config files of Datanode
            template:
                    src: hdfs-data.xml.j2
                    dest: /etc/hadoop/hdfs-site.xml

          - template:
                    src: core-site-data.xml.j2
                    dest: /etc/hadoop/core-site.xml
          - name: Starting Datanode
            command: hadoop-daemon.sh start datanode
               

