- hosts: all
  vars:
        jdk: jdk-8u171-linux-x64.rpm
        hadoop: hadoop-1.2.1-1.x86_64.rpm
  tasks:
          - name: Copying Hadoop and JDK packages
            copy:
                    src: /root/Hadoop_rpm/
                    dest: /root/
          - name: Installing JDK
            command: rpm -ivh "{{jdk}}"
          - name: Installing Hadoop
            command: rpm -ivh "{{hadoop}}" --force 



